apiVersion: v1
kind: Service
metadata:
  name: orderdeliverymanagement
  labels:
    app: orderdeliverymanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: orderdeliverymanagement
